INSERT INTO Categories (category_id, category_name) VALUES
(1, 'Electronics'),
(2, 'Books'),
(3, 'Clothing'),
(4, 'Home & Kitchen'),
(5, 'Sports & Outdoors'),
(6, 'Toys & Games'),
(7, 'Health & Beauty'),
(8, 'Automotive'),
(9, 'Music'),
(10, 'Movies & TV'),
(11, 'Pet Supplies'),
(12, 'Baby Products'),
(13, 'Garden & Outdoor'),
(14, 'Office Products'),
(15, 'Tools & Home Improvement'),
(16, 'Grocery & Gourmet Food'),
(17, 'Arts, Crafts & Sewing'),
(18, 'Industrial & Scientific'),
(19, 'Software'),
(20, 'Video Games'),
(21, 'Jewelry'),
(22, 'Watches'),
(23, 'Shoes'),
(24, 'Handbags & Wallets'),
(25, 'Luggage & Travel Gear'),
(26, 'Personal Care'),
(27, 'Luxury Beauty'),
(28, 'Collectibles & Fine Art'),
(29, 'Musical Instruments'),
(30, 'Cell Phones & Accessories'),
(31, 'Computers & Accessories'),
(32, 'Camera & Photo'),
(33, 'Video & DVD'),
(34, 'Television & Video'),
(35, 'GPS & Navigation'),
(36, 'Office Furniture'),
(37, 'Bedding'),
(38, 'Kitchen & Dining'),
(39, 'Bath'),
(40, 'Storage & Organization'),
(41, 'Furniture'),
(42, 'Mattresses & Box Springs'),
(43, 'Lighting & Ceiling Fans'),
(44, 'Kids & Baby'),
(45, 'Heating, Cooling & Air Quality'),
(46, 'Vacuums & Floor Care'),
(47, 'Irons & Steamers'),
(48, 'Appliances'),
(49, 'Power & Hand Tools'),
(50, 'Patio, Lawn & Garden');